[package]
name = "multicast-demo"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.96"
socket2 = { version = "0.5.8", features = ["all"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
